name: alimenta_ai
description: "A new Flutter project."

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  animated_text_kit: ^4.2.2
  http: ^1.3.0
  intl: ^0.20.2
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  file_picker: ^10.1.9
  record: ^5.0.4
  just_audio: ^0.9.35
  dio: ^5.4.0
  mime: ^1.0.4
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.9
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/seta_esquerda.svg
    - assets/icons/
    - assets/icons_bar/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon_final.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon_final.png
